module.exports = cities = [
  { id: 0, value: "Ain Harrouda" },
  { id: 1, value: "Ben Yakhlef" },
  { id: 2, value: "Bouskoura" },
  { id: 3, value: "Casablanca" },
  { id: 4, value: "Mediouna" },
  { id: 5, value: "Mohammadia" },
  { id: 6, value: "Tit Mellil" },
  { id: 7, value: "Ben Yakhlef" },
  { id: 8, value: "Bejaad" },
  { id: 9, value: "Ben Ahmed" },
  { id: 10, value: "Benslimane" },
  { id: 11, value: "Berrechid" },
  { id: 12, value: "Boujniba" },
  { id: 13, value: "Boulanouare" },
  { id: 14, value: "Bouznika" },
  { id: 15, value: "Deroua" },
  { id: 16, value: "El Borouj" },
  { id: 17, value: "El Gara" },
  { id: 18, value: "Guisser" },
  { id: 19, value: "Hattane" },
  { id: 20, value: "Khouribga" },
  { id: 21, value: "Loulad" },
  { id: 22, value: "Oued Zem" },
  { id: 23, value: "Oulad Abbou" },
  { id: 24, value: "Oulad HRiz Sahel" },
  { id: 25, value: "Oulad Mrah" },
  { id: 26, value: "Oulad Said" },
  { id: 27, value: "Oulad Sidi Ben Daoud" },
  { id: 28, value: "Ras El Ain" },
  { id: 29, value: "Settat" },
  { id: 30, value: "Sidi Rahhal Chatai" },
  { id: 31, value: "Soualem" },
  { id: 32, value: "Azemmour" },
  { id: 33, value: "Bir Jdid" },
  { id: 34, value: "Bouguedra" },
  { id: 35, value: "Echemmaia" },
  { id: 36, value: "El Jadida" },
  { id: 37, value: "Hrara" },
  { id: 38, value: "Ighoud" },
  { id: 39, value: "Jamaat Shaim" },
  { id: 40, value: "Jorf Lasfar" },
  { id: 41, value: "Khemis Zemamra" },
  { id: 42, value: "Laaounate" },
  { id: 43, value: "Moulay Abdallah" },
  { id: 44, value: "Oualidia" },
  { id: 45, value: "Oulad Amrane" },
  { id: 46, value: "Oulad Frej" },
  { id: 47, value: "Oulad Ghadbane" },
  { id: 48, value: "Safi" },
  { id: 49, value: "Sebt El Maarif" },
  { id: 50, value: "Sebt Gzoula" },
  { id: 51, value: "Sidi Ahmed" },
  { id: 52, value: "Sidi Ali Ban Hamdouche" },
  { id: 53, value: "Sidi Bennour" },
  { id: 54, value: "Sidi Bouzid" },
  { id: 55, value: "Sidi Smail" },
  { id: 56, value: "Youssoufia" },
  { id: 57, value: "Fès" },
  { id: 58, value: "Ain Cheggag" },
  { id: 59, value: "Bhalil" },
  { id: 60, value: "Boulemane" },
  { id: 61, value: "El Menzel" },
  { id: 62, value: "Guigou" },
  { id: 63, value: "Imouzzer Kandar" },
  { id: 64, value: "Imouzzer Marmoucha" },
  { id: 65, value: "Missour" },
  { id: 66, value: "Moulay Yaacoub" },
  { id: 67, value: "Ouled Tayeb" },
  { id: 68, value: "Outat El Haj" },
  { id: 69, value: "Ribate El Kheir" },
  { id: 70, value: "Sefrou" },
  { id: 71, value: "Skhinate" },
  { id: 72, value: "Tafajight" },
  { id: 73, value: "Arbaoua" },
  { id: 74, value: "Ain Dorij" },
  { id: 75, value: "Dar Gueddari" },
  { id: 76, value: "Had Kourt" },
  { id: 77, value: "Jorf El Melha" },
  { id: 78, value: "Kenitra" },
  { id: 79, value: "Khenichet" },
  { id: 80, value: "Lalla Mimouna" },
  { id: 81, value: "Mechra Bel Ksiri" },
  { id: 82, value: "Mehdia" },
  { id: 83, value: "Moulay Bousselham" },
  { id: 84, value: "Sidi Allal Tazi" },
  { id: 85, value: "Sidi Kacem" },
  { id: 86, value: "Sidi Slimane" },
  { id: 87, value: "Sidi Taibi" },
  { id: 88, value: "Sidi Yahya El Gharb" },
  { id: 89, value: "Souk El Arbaa" },
  { id: 90, value: "Akka" },
  { id: 91, value: "Assa" },
  { id: 92, value: "Bouizakarne" },
  { id: 93, value: "El Ouatia" },
  { id: 94, value: "Es-Semara" },
  { id: 95, value: "Fam El Hisn" },
  { id: 96, value: "Foum Zguid" },
  { id: 97, value: "Guelmim" },
  { id: 98, value: "Taghjijt" },
  { id: 99, value: "Tan-Tan" },
  { id: 100, value: "Tata" },
  { id: 101, value: "Zag" },
  { id: 102, value: "Marrakech" },
  { id: 103, value: "Ait Daoud" },
  { id: 104, value: "Amizmiz" },
  { id: 105, value: "Assahrij" },
  { id: 106, value: "Ait Ourir" },
  { id: 107, value: "Ben Guerir" },
  { id: 108, value: "Chichaoua" },
  { id: 109, value: "El Hanchane" },
  { id: 110, value: "El Kelaa des Sraghna" },
  { id: 111, value: "Essaouira" },
  { id: 112, value: "Fraita" },
  { id: 113, value: "Ghmate" },
  { id: 114, value: "Ighounane" },
  { id: 115, value: "Imintanoute" },
  { id: 116, value: "Kattara" },
  { id: 117, value: "Lalla Takerkoust" },
  { id: 118, value: "Loudaya" },
  { id: 119, value: "Laattaouia" },
  { id: 120, value: "Moulay Brahim" },
  { id: 121, value: "Mzouda" },
  { id: 122, value: "Ounagha" },
  { id: 123, value: "Sid LMokhtar" },
  { id: 124, value: "Sid Zouin" },
  { id: 125, value: "Sidi Abdallah Ghiat" },
  { id: 126, value: "Sidi Bou Othmane" },
  { id: 127, value: "Sidi Rahhal" },
  { id: 128, value: "Skhour Rehamna" },
  { id: 129, value: "Smimou" },
  { id: 130, value: "Tafetachte" },
  { id: 131, value: "Tahannaout" },
  { id: 132, value: "Talmest" },
  { id: 133, value: "Tamallalt" },
  { id: 134, value: "Tamanar" },
  { id: 135, value: "Tamansourt" },
  { id: 136, value: "Tameslouht" },
  { id: 137, value: "Tanalt" },
  { id: 138, value: "Zeubelemok" },
  { id: 139, value: "Meknès‎" },
  { id: 140, value: "Khenifra" },
  { id: 141, value: "Agourai" },
  { id: 142, value: "Ain Taoujdate" },
  { id: 143, value: "MyAliCherif" },
  { id: 144, value: "Rissani" },
  { id: 145, value: "Amalou Ighriben" },
  { id: 146, value: "Aoufous" },
  { id: 147, value: "Arfoud" },
  { id: 148, value: "Azrou" },
  { id: 149, value: "Ain Jemaa" },
  { id: 150, value: "Ain Karma" },
  { id: 151, value: "Ain Leuh" },
  { id: 152, value: "Ait Boubidmane" },
  { id: 153, value: "Ait Ishaq" },
  { id: 154, value: "Boudnib" },
  { id: 155, value: "Boufakrane" },
  { id: 156, value: "Boumia" },
  { id: 157, value: "El Hajeb" },
  { id: 158, value: "Elkbab" },
  { id: 159, value: "Er-Rich" },
  { id: 160, value: "Errachidia" },
  { id: 161, value: "Gardmit" },
  { id: 162, value: "Goulmima" },
  { id: 163, value: "Gourrama" },
  { id: 164, value: "Had Bouhssoussen" },
  { id: 165, value: "Haj Kaddour" },
  { id: 166, value: "Ifrane" },
  { id: 167, value: "Itzer" },
  { id: 168, value: "Jorf" },
  { id: 169, value: "Kehf Nsour" },
  { id: 170, value: "Kerrouchen" },
  { id: 171, value: "Mhaya" },
  { id: 172, value: "Mrirt" },
  { id: 173, value: "Midelt" },
  { id: 174, value: "Moulay Ali Cherif" },
  { id: 175, value: "Moulay Bouazza" },
  { id: 176, value: "Moulay Idriss Zerhoun" },
  { id: 177, value: "Moussaoua" },
  { id: 178, value: "NZalat Bni Amar" },
  { id: 179, value: "Ouaoumana" },
  { id: 180, value: "Oued Ifrane" },
  { id: 181, value: "Sabaa Aiyoun" },
  { id: 182, value: "Sebt Jahjouh" },
  { id: 183, value: "Sidi Addi" },
  { id: 184, value: "Tichoute" },
  { id: 185, value: "Tighassaline" },
  { id: 186, value: "Tighza" },
  { id: 187, value: "Timahdite" },
  { id: 188, value: "Tinejdad" },
  { id: 189, value: "Tizguite" },
  { id: 190, value: "Toulal" },
  { id: 191, value: "Tounfite" },
  { id: 192, value: "Zaouia dIfrane" },
  { id: 193, value: "Zaida" },
  { id: 194, value: "Ahfir" },
  { id: 195, value: "Aklim" },
  { id: 196, value: "Al Aroui" },
  { id: 197, value: "Ain Bni Mathar" },
  { id: 198, value: "Ain Erreggada" },
  { id: 199, value: "Ben Taieb" },
  { id: 200, value: "Berkane" },
  { id: 201, value: "Bni Ansar" },
  { id: 202, value: "Bni Chiker" },
  { id: 203, value: "Bni Drar" },
  { id: 204, value: "Bni Tadjite" },
  { id: 205, value: "Bouanane" },
  { id: 206, value: "Bouarfa" },
  { id: 207, value: "Bouhdila" },
  { id: 208, value: "Dar El Kebdani" },
  { id: 209, value: "Debdou" },
  { id: 210, value: "Douar Kannine" },
  { id: 211, value: "Driouch" },
  { id: 212, value: "El Aioun Sidi Mellouk" },
  { id: 213, value: "Farkhana" },
  { id: 214, value: "Figuig" },
  { id: 215, value: "Ihddaden" },
  { id: 216, value: "Jaadar" },
  { id: 217, value: "Jerada" },
  { id: 218, value: "Kariat Arekmane" },
  { id: 219, value: "Kassita" },
  { id: 220, value: "Kerouna" },
  { id: 221, value: "Laatamna" },
  { id: 222, value: "Madagh" },
  { id: 223, value: "Midar" },
  { id: 224, value: "Nador" },
  { id: 225, value: "Naima" },
  { id: 226, value: "Oued Heimer" },
  { id: 227, value: "Oujda" },
  { id: 228, value: "Ras El Ma" },
  { id: 229, value: "Saidia" },
  { id: 230, value: "Selouane" },
  { id: 231, value: "Sidi Boubker" },
  { id: 232, value: "Sidi Slimane Echcharaa" },
  { id: 233, value: "Talsint" },
  { id: 234, value: "Taourirt" },
  { id: 235, value: "Tendrara" },
  { id: 236, value: "Tiztoutine" },
  { id: 237, value: "Touima" },
  { id: 238, value: "Touissit" },
  { id: 239, value: "Zaio" },
  { id: 240, value: "Zeghanghane" },
  { id: 241, value: "Rabat" },
  { id: 242, value: "Sale" },
  { id: 243, value: "Ain El Aouda" },
  { id: 244, value: "Harhoura" },
  { id: 245, value: "Khemisset" },
  { id: 246, value: "Oulmès" },
  { id: 247, value: "Rommani" },
  { id: 248, value: "Sidi Allal El Bahraoui" },
  { id: 249, value: "Sidi Bouknadel" },
  { id: 250, value: "Skhirate" },
  { id: 251, value: "Tamesna" },
  { id: 252, value: "Temara" },
  { id: 253, value: "Tiddas" },
  { id: 254, value: "Tiflet" },
  { id: 255, value: "Touarga" },
  { id: 256, value: "Agadir" },
  { id: 257, value: "Agdz" },
  { id: 258, value: "Agni Izimmer" },
  { id: 259, value: "Ait Melloul" },
  { id: 260, value: "Alnif" },
  { id: 261, value: "Anzi" },
  { id: 262, value: "Aoulouz" },
  { id: 263, value: "Aourir" },
  { id: 264, value: "Arazane" },
  { id: 265, value: "Ait Baha" },
  { id: 266, value: "Ait Iaaza" },
  { id: 267, value: "Ait Yalla" },
  { id: 268, value: "Ben Sergao" },
  { id: 269, value: "Biougra" },
  { id: 270, value: "Boumalne-Dadès" },
  { id: 271, value: "Dcheira El Jihadia" },
  { id: 272, value: "Drargua" },
  { id: 273, value: "El Guerdane" },
  { id: 274, value: "Harte Lyamine" },
  { id: 275, value: "Ida Ougnidif" },
  { id: 276, value: "Ifri" },
  { id: 277, value: "Igdamen" },
  { id: 278, value: "Ighil nOumgoun" },
  { id: 279, value: "Imassine" },
  { id: 280, value: "Inezgane" },
  { id: 281, value: "Irherm" },
  { id: 282, value: "Kelaat-MGouna" },
  { id: 283, value: "khmiss Ait Amira" },
  { id: 284, value: "Lakhsas" },
  { id: 285, value: "Lakhsass" },
  { id: 286, value: "Lqliaa" },
  { id: 287, value: "Msemrir" },
  { id: 288, value: "MassaMaroc" },
  { id: 289, value: "Megousse" },
  { id: 290, value: "Ouarzazate" },
  { id: 291, value: "Oulad Berhil" },
  { id: 292, value: "Oulad Teima" },
  { id: 293, value: "Sarghine" },
  { id: 294, value: "Sidi Ifni" },
  { id: 295, value: "Skoura" },
  { id: 296, value: "Tabounte" },
  { id: 297, value: "Tafraout" },
  { id: 298, value: "Taghzout" },
  { id: 299, value: "Tagzen" },
  { id: 300, value: "Taliouine" },
  { id: 301, value: "Tamegroute" },
  { id: 302, value: "Tamraght" },
  { id: 303, value: "Tanoumrite Nkob Zagora" },
  { id: 304, value: "Taourirt ait zaghar" },
  { id: 305, value: "Taroudannt" },
  { id: 306, value: "Temsia" },
  { id: 307, value: "Tifnit" },
  { id: 308, value: "Tisgdal" },
  { id: 309, value: "Tiznit" },
  { id: 310, value: "Toundoute" },
  { id: 311, value: "Zagora" },
  { id: 312, value: "Afourar" },
  { id: 313, value: "Aghbala" },
  { id: 314, value: "Azilal" },
  { id: 315, value: "Ait Majden" },
  { id: 316, value: "Beni Ayat" },
  { id: 317, value: "Beni Mellal" },
  { id: 318, value: "Bin elouidane" },
  { id: 319, value: "Bradia" },
  { id: 320, value: "Bzou" },
  { id: 321, value: "Dar Oulad Zidouh" },
  { id: 322, value: "Demnate" },
  { id: 323, value: "Draa" },
  { id: 324, value: "El Ksiba" },
  { id: 325, value: "Foum Jamaa" },
  { id: 326, value: "Fquih Ben Salah" },
  { id: 327, value: "Kasba Tadla" },
  { id: 328, value: "Ouaouizeght" },
  { id: 329, value: "Oulad Ayad" },
  { id: 330, value: "Oulad MBarek" },
  { id: 331, value: "Oulad Yaich" },
  { id: 332, value: "Sidi Jaber" },
  { id: 333, value: "Souk Sebt Oulad Nemma" },
  { id: 334, value: "Zaouiat Cheikh" },
  { id: 335, value: "Tanger‎" },
  { id: 336, value: "Tetouan‎" },
  { id: 337, value: "Akchour" },
  { id: 338, value: "Assilah" },
  { id: 339, value: "Bab Berred" },
  { id: 340, value: "Bab Taza" },
  { id: 341, value: "Brikcha" },
  { id: 342, value: "Chefchaouen" },
  { id: 343, value: "Dar Bni Karrich" },
  { id: 344, value: "Dar Chaoui" },
  { id: 345, value: "Fnideq" },
  { id: 346, value: "Gueznaia" },
  { id: 347, value: "Jebha" },
  { id: 348, value: "Karia" },
  { id: 349, value: "Khemis Sahel" },
  { id: 350, value: "Ksar El Kebir" },
  { id: 351, value: "Larache" },
  { id: 352, value: "Mdiq" },
  { id: 353, value: "Martil" },
  { id: 354, value: "Moqrisset" },
  { id: 355, value: "Oued Laou" },
  { id: 356, value: "Oued Rmel" },
  { id: 357, value: "Ouazzane" },
  { id: 358, value: "Point Cires" },
  { id: 359, value: "Sidi Lyamani" },
  { id: 360, value: "Sidi Mohamed ben Abdallah el-Raisuni" },
  { id: 361, value: "Zinat" },
  { id: 362, value: "Ajdir‎" },
  { id: 363, value: "Aknoul‎" },
  { id: 364, value: "Al Hoceima‎" },
  { id: 365, value: "Ait Hichem‎" },
  { id: 366, value: "Bni Bouayach‎" },
  { id: 367, value: "Bni Hadifa‎" },
  { id: 368, value: "Ghafsai‎" },
  { id: 369, value: "Guercif‎" },
  { id: 370, value: "Imzouren‎" },
  { id: 371, value: "Inahnahen‎" },
  { id: 372, value: "IssaguenKetama ‎" },
  { id: 373, value: "KariaEl Jadida ‎" },
  { id: 374, value: "Karia Ba Mohamed‎" },
  { id: 375, value: "Oued Amlil‎" },
  { id: 376, value: "Oulad Zbair‎" },
  { id: 377, value: "Tahla‎" },
  { id: 378, value: "Tala Tazegwaght‎" },
  { id: 379, value: "Tamassint‎" },
  { id: 380, value: "Taounate‎" },
  { id: 381, value: "Targuist‎" },
  { id: 382, value: "Taza‎" },
  { id: 383, value: "Tainaste‎" },
  { id: 384, value: "Thar Es-Souk‎" },
  { id: 385, value: "Tissa‎" },
  { id: 386, value: "Tizi Ouasli‎" },
  { id: 387, value: "Laayoune‎" },
  { id: 388, value: "El Marsa‎" },
  { id: 389, value: "Tarfaya‎" },
  { id: 390, value: "Boujdour‎" },
  { id: 391, value: "Awsard" },
  { id: 392, value: "Oued-Eddahab" },
  { id: 393, value: "Stehat" }
];
